### ISSUE TITLE
How to run the e2e tests locally?

### ISSUE THREAD

**Issue by andreas-aeschlimann** [dasch-swiss/knora-api-js-lib-test#20]
I am getting this:

```
npm run e2e

> knora-api-js-lib-test@0.0.0 e2e /Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test
> ng e2e --prod=true --protractor-config=./e2e/protractor.conf.js --webdriver-update=false

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locallly.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {0} runtime.e8a2810b3b08d6a1b6aa.js (runtime) 2.83 kB [entry] [rendered]
chunk {1} main.795b2c884bd385a5bf31.js (main) 1.56 MB [initial] [rendered]
chunk {2} polyfills.9f117ca36926296de984.js (polyfills) 64.3 kB [initial] [rendered]
chunk {3} styles.09e2c710755c8867a460.css (styles) 0 bytes [initial] [rendered]
Date: 2019-10-29T22:20:51.579Z - Hash: 6178f1dda22a38010f15 - Time: 16919ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Compiled successfully.
[23:20:51] I/launcher - Running 1 instances of WebDriver
[23:20:51] I/direct - Using ChromeDriver directly...
[23:20:51] E/direct - Error code: 135
[23:20:51] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[23:20:51] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at Direct.getNewDriver (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/protractor/built/driverProviders/direct.js:63:31)
    at Runner.createBrowser (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:834:54)
    at /Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:796:13)
    at /Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:556:49
    at runSingle (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:137:13)
    at flush (/Users/andreas/Documents/GIT/andreas-aeschlimann@github.com/dhlab-basel/knora-api-js-lib-test/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[23:20:51] E/launcher - Process exited with error code 135
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! knora-api-js-lib-test@0.0.0 e2e: `ng e2e --prod=true --protractor-config=./e2e/protractor.conf.js --webdriver-update=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the knora-api-js-lib-test@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by tobiasschweizer** [comment]
before running the e2e tests you have to run: `npm run webdriver-update`, see https://github.com/dasch-swiss/knora-api-js-lib-test/blob/815cb8c95012e1cb096aa97c495c434528c6b140/.travis.yml#L43-L46

**Comment by tobiasschweizer** [comment]
see https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/continuous-integration.md#chromedriver

**Comment by tobiasschweizer** [comment]
e2e tests require a running Knora. Follow the instructions given in https://github.com/dasch-swiss/knora-api-js-lib-test/blob/815cb8c95012e1cb096aa97c495c434528c6b140/.travis.yml

**Comment by tobiasschweizer** [comment]
not reproducible, works for me
